apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  containers:
    - name: app
      image: node:20
      securityContext:
        privileged: false  # ✅ Prevent root access
        runAsNonRoot: true  # ✅ Run as a non-root user
        readOnlyRootFilesystem: true  # ✅ Prevent filesystem modification
