name: Trivy Security Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  trivy:
    name: Run Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t my-test-image .

      - name: Run Trivy Scan on Public Image (nginx:latest)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'nginx:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          ignorefile: '.trivyignore'
          ignore-unfixed: true  # Ignore issues without a known fix
          exit-code: '1'
